POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Novo curso 2"
}

###

GET http://localhost:3333/courses


###


GET http://localhost:3333/courses/9b7a3b84-62f5-4a4b-9523-c5f888b8baf2


